### ISSUE TITLE
ス○ブラと巨乳を愛する会 (あき) 

### ISSUE THREAD

**Issue by e0972951006** [mnao305/fantia-img-dl-tool#30]
https://fantia.jp/posts/205729
https://fantia.jp/posts/210318
https://fantia.jp/posts/135591

**Comment by e0972951006** [comment]
> https://fantia.jp/posts/210318
> https://fantia.jp/posts/210318
> https://fantia.jp/posts/135591

**Comment by mnao305** [comment]
What's the issue?

**Comment by e0972951006** [comment]
@mnao305 Can you download the three-picture code

**Comment by mnao305** [comment]
Hmm, I don't know what the problem is.

If you add the browser extension, you'll see a button, just click on it.
Note that this only works if you have multiple images posted.

**Comment by e0972951006** [comment]
!
![CE9BEA97-1AE2-4E23-B097-EBBA23A88600](https://user-images.githubusercontent.com/70758801/115290252-e9ca3e80-a185-11eb-9576-48598381bb36.jpeg)
[97212FBA-3E59-40A8-80E1-25E461DFA63A](https://user-images.githubusercontent.com/70758801/115290235-e636b780-a185-11eb-9123-518891d67656.jpeg)
![500073FE-5646-49D9-9663-EC400F686B4D](https://user-images.githubusercontent.com/70758801/115290246-e8991180-a185-11eb-9080-0ac5519fb433.jpeg)

**Comment by e0972951006** [comment]
@mnao305 
![Uploading 9092F2A3-E357-4966-A686-18759213BD25.jpeg…]()

**Comment by e0972951006** [comment]
@mnao305 yes
