### ISSUE TITLE
https://fantia.jp/posts/210318

### ISSUE THREAD

**Issue by e0972951006** [mnao305/fantia-img-dl-tool#31]
@mnao305 I’m sorry That’s why I helped download pictures
https://fantia.jp/posts/210318 ok

**Comment by mnao305** [comment]
@e0972951006 
What is the problem?

Do you have any browser extensions installed?
https://chrome.google.com/webstore/detail/fantia-img-dl-tool/poaolllddjlbbomnohpahbpdlcklkffi

Is your image gallery showing up on Fantia?
(If the post is for a paid plan only, have you joined?)

Is the DL button visible below the image gallery?

**Comment by e0972951006** [comment]
@mnao305 I’m sorry I iPhone

**Comment by mnao305** [comment]
Oh, I see.
I'm sorry, but this program is for PC Chrome browsers only.

I will close this issue.

**Comment by e0972951006** [comment]
@mnao305 you There are other methods like mobile phones 📱  https://fantia.jp/posts/210318

**Comment by e0972951006** [comment]
@mnao305 Download pictures after we have trouble for you, upload ok https://fantia.jp/posts/210318

**Comment by e0972951006** [comment]
You pc chromoe
I iPhone chomoe @mnao305

**Comment by mnao305** [comment]
@e0972951006 
I'm sorry, but I don't know what you're talking about.

Also, we can't give the downloaded images to you. There are some rights issues.

**Comment by e0972951006** [comment]
@mnao305 Yes

**Comment by e0972951006** [comment]
On

**Comment by e0972951006** [comment]
I use Chinese ㄧ sentence 試試看 ok

**Comment by e0972951006** [comment]
@mnao305 I use Chinese ㄧ sentence 試試看 ok
