### ISSUE TITLE
https://fantia.jp/posts/210318

### ISSUE THREAD

**Issue by a940802a** [mnao305/fantia-img-dl-tool#34]
@mnao305  download https://fantia.jp/posts/210318 img

**Comment by mnao305** [comment]
What's the issue?

**Comment by a940802a** [comment]
you discord ?

**Comment by a940802a** [comment]
@mnao305 Do you have discord

**Comment by mnao305** [comment]
no.

**Comment by mnao305** [comment]
Uh, are you the person who sent me an Issue the other day?

I can't download it for you.

**Comment by a940802a** [comment]
Yes

**Comment by a940802a** [comment]
@mnao305 yes
